### PR TITLE
Allow using qualified names in TH

### PR DESCRIPTION
**Pull request by Yurry**
Currently Generics.SOP.TH loses the qualification of the type name, e.g.
`deriveGeneric ''Foo.Bar` generates the code just for `Bar`, which leads to name clashes when `Foo` imports another `Bar`. This is solved by using the passed type name instead of re-extracting it from the type definition.

### CODE REVIEW

**Comment by phadej** [comment]
@RyanGlScott do you have an idea how this can be solved?

**Comment by kosmikus** [comment]
I'm trying to find a minimal test case for the problem this is supposed to fix. It looks to me as if `reifyDatatype` produces a qualified name if needed.

**Comment by RyanGlScott** [comment]
I can't recommend a solution because I don't yet understand what the problem is. The PR description is too vague for me to make a judgment one way or the other. A minimal example of the issue would be helpful.

**Comment by Yurry** [comment]
I'm sorry, @kosmikus is right and the problem with name clashes is our module was not caused by generics-sop at all. I'll close the PR, sorry for taking your time again 🙏

**Pull request closed without merging**
