### PR TITLE
Type-level meta data

### PR DESCRIPTION
**Pull request by kosmikus**
Don't merge just yet. This is still work in progress.

As requested by @phadej in #30.

This is as it is right now. I will try to add more comments and explanations of the approach.

### CODE REVIEW

**Comment by kosmikus** [comment]
CI failures are due to the build failing on ghc-7. I'm pretty sure this is unavoidable, although I'm trying to remove some of the non-necessary items that break compatibility with ghc-7 to see if there is some form of compromise possible.

**Comment by phadej** [comment]
If GHC-7.x could be supported without metadata (e.g. deriving only `SOP.Generic` from `GHC.Generic`) that would be good compromise, IMHO. And using *TemplateHaskell* there shouldn't be any problem to derive codes. So if we don't need `TypeInType` to work with new stuff (or other only GHC-8.x functionality) that would be great

**Comment by kosmikus** [comment]
I'm not convinced that supporting one compiler version with partial functionality (i.e., having a compiler-version-dependent package interface) is a good idea.

**Comment by phadej** [comment]
Ok, let's not have partiality; There's few packages I'm involved with in http://packdeps.haskellers.com/reverse/generics-sop

I'd try to test them against new version

**Comment by kosmikus** [comment]
Yes, that would be good, thanks. I can test a few reverse dependencies, too.

**Comment by kosmikus** [comment]
@phadej I'm still undecided regarding what GHC versions to support in 0.3. But I have re-worked this branch so that it should support everything from GHC 7.8 up (GHC 7.6 would still have to be dropped, but that seems uncritical now anyway).

TH generation of type-level metadata should in principle work for all these versions. For GGP-derived instances with GHC < 8, you would only get term-level metadata.

Since the interface partiality concerns only new functionality, this might be an acceptable compromise. Nothing is tested very much yet, though.

**Comment by kosmikus** [comment]
@phadej I ran superficial tests for most reverse dependencies (i.e., tried to build them, nothing further). I found one bug which was a missing case in a type function, triggered by binary-tagged. This is now fixed. All packages I try seem to actually work without any code changes. I tested with ghc-8.0.2 and ghc-7.10.3.

Do you have further things you want to test?

**Comment by phadej** [comment]
@kosmikus I tried to build our work project, it compiled with both 7.10.3 and 8.0.2; tests pass too. And clients compiled with this branch work against servers compiled with Hackage version. There are few things using term-level metadata.

So, for me this looks very good!

**Comment by kosmikus** [comment]
@phadej Ok, thanks! Then my current plan is to rebase this and make a 0.3.0.0 release with just this change sometime during the week.

**Comment by phadej** [comment]
@kosmikus great!

**Pull request merged**
