### PR TITLE
Add Monoid instances for basic functors, NP, POP.

### PR DESCRIPTION
**Pull request by kosmikus**
Inspired by https://stackoverflow.com/a/45523136/1482749

Still needs since-annotations before it can be merged, but it otherwise doesn't seem very controversial to me.

/cc @phadej @danidiaz

### CODE REVIEW

**Comment by phadej** [comment]
We should add `Semigroup` instances too then, otherwise :+1:

**Comment by kosmikus** [comment]
@phadej Isn't `Semigroup` far more complicated though? We then get another dependency or a conditional interface again.

**Comment by phadej** [comment]
@kosmikus I cannot find the page on ghc trac, but https://prime.haskell.org/wiki/Libraries/Proposals says that GHC will warn about `Monoid` without `Semigroup` already in GHC-8.4.

**Comment by kosmikus** [comment]
@phadej The dependency footprint of semigroups is rather heavy though. I'd prefer not to have to depend on it. And if GHC only starts *warning* about `Monoid` without `Semigroup` in 8.4, then it's still rather far away.

**Comment by phadej** [comment]
We can have `flag semigroups` if someone don't want the dependency for `!(ghc>= 8.0)`.

**Comment by kosmikus** [comment]
@phadej I'm afraid this still doesn't convince me. I'd rather just avoid doing `Semigroup` at all. Are you still in support of merging the PR under these circumstances?

**Comment by phadej** [comment]
I'm not against. Let's see if anyone else would need `Semigroup` instance.

**Comment by phadej** [comment]
FWIW, GHC-8.4 (and current GHC-HEAD) already has `class Semigroup m => Monoid m`

**Comment by kosmikus** [comment]
I'm going to shift this to 0.4. I'm planning to make 0.4 require 8.0 or later, so this will avoid the problems with semigroups.

**Comment by kosmikus** [comment]
Superseded by #79.

**Pull request closed without merging**
