### PR TITLE
Doctests

### PR DESCRIPTION
**Pull request by phadej**
Let's wait till https://github.com/sol/doctest/pull/163 is accepted (or rejected), so we can undo `it` changes, which would be very nice to undo.

### CODE REVIEW

**Comment by phadej** [comment]
@kosmikus I'm not sure whether the last is a real bug, or just dummy GHC.

**Comment by kosmikus** [comment]
Thanks. I'm in principle ok to merge even like this.

**Comment by phadej** [comment]
@kosmikus now using `doctest-0.12` which supports `it`!

**Comment by kosmikus** [comment]
@phadej Feel free to merge if you're confident this is all good.

**Comment by phadej** [comment]
I hope that `doctest` won't get new major release in a meanwhile :)

I'm looking forward for new `Show` instance

**Pull request merged**
