### PR TITLE
Simple benchmark framework.

### PR DESCRIPTION
**Pull request by andorp**

### CODE REVIEW

**Comment by phadej** [comment]
`weight` is 7.8 compatible. https://matrix.hackage.haskell.org/package/weigh (there's something wrong with last release though, I'll fix the metadata).

**Comment by phadej** [comment]
@andorp try to enable benchmarks with 7.8.4 again.

**Comment by kosmikus** [comment]
@andorp Thanks for working on this. The timing is great. I've actually just started to look at this PR again myself. I intend to merge it soon, and then release a new version of generics-sop.

**Comment by kosmikus** [comment]
Sorry once again for the delay. I've looked at this once again, but unfortunately, I'm not convinced yet that the benchmarks are "correct". I don't understand the way the different tree types are constructed. It looks like they're newtype wrappers around a recursive datatype. For the inner recursive datatype, both `Eq` and `Show` are derived. Doesn't this mean that only a single outer invocation is using the specifically defined instance, and all the recursive calls are using the derived instance?

**Comment by kosmikus** [comment]
The current plan here is to not use the current PR, but the revised stuff in `wip/benchmark` and `wip/inspection-testing-bench`, which is in parts based on this PR, but substantially changed. After 0.4 is out, I'll make another attempt to get that merged.

**Comment by kosmikus** [comment]
Fixed via #84. @andorp Thanks again for your help with this, even though in the end I rewrote most of what you did. Let me know if you'd like to have some kind of acknowledgement, because your original commits now unfortunately do not show. Perhaps I should create a CREDITS file.

**Comment by andorp** [comment]
@kosmikus I am happy that the idea we discussed was a good one. Thanks for taking this over. I don't feel that only for the lost commits we should open a CREDITS file. If you have more reason to open one than just this particular instance, I wouldn't mind listed in it.

**Pull request closed without merging**
