### PR TITLE
re-export collapse_NP and collapse_POP

### PR DESCRIPTION
**Pull request by ocramz**

### CODE REVIEW

**Comment by ocramz** [comment]
I didn't check whether other `sop-core` functions are not re-exported by `generics-sop`, just noticed these two missing. Or is it intentional?

**Comment by phadej** [comment]
I think `_NP` etc specialised functions aren't exported on purpose

**Comment by ocramz** [comment]
@phadej hmm but this means a user must import both generics-sop and sop-core :/

**Comment by phadej** [comment]
@ocramz `Generics.SOP.NP` is in `generics-sop`.

**Comment by ocramz** [comment]
OMG, you're right. Sorry!

**Comment by phadej** [comment]
no worries

**Pull request closed without merging**
