### PR TITLE
WIP: Make K & I type/pattern synonyms

### PR DESCRIPTION
**Pull request by alexfmpe**
Since the cabal files require `base >= 4.9` nowadays (meaning `Const` & `Compose` are poly-kinded) I tried to switch `K`, `I`, `:.:` to synonyms, though I ran into some issues which make this less viable than I originally thought:

1. The Show/Read instances become different, which I guess could break serialization-related code.
```
> I ""
Identity ""

> I ""
I ""
```

2. `Complete` pragma only shows up in GHC 8.2, so this would have to either wait until 8.0 support is dropped and/or disable exhaustiveness checks in this module.

3. `Data.SOP.Constraint.Compose` has a name collision with `Data.Functor.Compose.Compose`. Not sure how to go about this.

### CODE REVIEW

**Comment by phadej** [comment]
doctests are indeed broken.

**Comment by kosmikus** [comment]
Thanks for the PR. I know it's somewhat unsatisfactory to have the duplicated constructors. However, at this point, I have to ask what the concrete advantages are we'd gain from making these pattern synonyms?

**Comment by alexfmpe** [comment]
It seems to me that code that imports `generics-sop` can have other instances for K/I in scope if they import other libs that define them. Though I'm not sure how much that matters in practice, especially weighted against the above issues. Might be best to close or let this PR simmer.

**Comment by kosmikus** [comment]
Yes, true, the instances for `Identity` and `I` can differ. I'm not sure whether that's a big problem in practice though. And it's still possible to `hcoerce` from e.g. `SOP I` to `SOP Identity`.

I'm still willing to have the discussion though. We could in principle, with a major version bump, switch to using the base newtype constructors now, but then I'd also advertise using them and provide the pattern synonyms merely for (limited) backwards compatibility.

**Pull request closed without merging**
