### PR TITLE
DeepSeq

### LINKED ISSUE #23: Add NFData instances
If no one picks this up, I'll do that around GHC8.2 time (after new `deepseq` release, with `NFData1/2`)

### PR DESCRIPTION
**Pull request by phadej**
Resolve #23

### CODE REVIEW

**Comment by kosmikus** [comment]
LGTM. I haven't carefully checked the whole CPP logic, but CI seems to say it's ok. Feel free to merge.

**Comment by phadej** [comment]
The CPP logic says that NFData1/2 are only available with deepseq >=1.4.3, should I add a comment about that?

**Comment by kosmikus** [comment]
Comments are rarely evil. :) But in principle, I think it's obvious enough without. What I primarily meant is that I haven't checked that it really builds with both an old and a new version of deepseq, and I haven't checked whether 1.4.3 is really the threshold for adding these instances.

**Comment by phadej** [comment]
It is, I know as I'm guilty for adding the classes to `deepseq`

**Comment by phadej** [comment]
I cannot "really" check whether this branch builds with deepseq-1.4.3 and non-GHC-8.2 compiler, as `deepseq-1.4.3` isn't yet published; but I don't see a reason why it wouldn't.

**Pull request merged**
