### PR TITLE
Add various metadata getters

### PR DESCRIPTION
**Pull request by phadej**
I needed those then once

- If you have better naming scheme, I'll happy to rename them
- Also didin't re-exported `G.SOP.Metatada` from `G.SOP`, but can do also.

### CODE REVIEW

**Comment by phadej** [comment]
(I don't remember whether I have getters as lens in `generics-sop-lens`, but sometimes I just cannot use it too)...

**Comment by kosmikus** [comment]
In principle, I agree that these are useful enough to make them part of the main package. Do we need the prefixes? Can we not just name them `constructorName` etc?

(There's also the issue that I may want to make a non-backward-compatible change for the metadata when lifting it all to the type level, which may affect these getters again. On the other hand, I'm not sure how soon I will get to it, so that's not a reason to hold this back.)

**Comment by phadej** [comment]
I chose prefix because of `diConstructorInfo :: DatatypeInfo xss -> NP ConstructorInfo xss` and `constructorInfo :: (HasDatatypeInfo a, xss ~ Code a) => proxy a -> NP ConstructorInfo xss` clash

**Comment by kosmikus** [comment]
I'd say drop the `HasDatatypeInfo` version.

I would like to add generic functions
```
constructorInfoOf :: (Generic a, HasDatatypeInfo a) => a -> ConstructorInfo
constructorIndexOf :: (Generic a, HasDatatypeInfo a) => a -> Int
```
and possibly more, though (should probably be a separate issue though).

**Comment by phadej** [comment]
I actually had
```hs
constructorNameOf :: NP ConstructorInfo xss -> NS f xss -> ConstructorName
```
in https://gist.github.com/phadej/e09205d0b798a08d283d4bf6d6d6eeb5

I'm not sure if `constructorInfoOf` is as useful, as you want to traverse `SOP I (Code a)` as well, when you have `a`...

**Comment by kosmikus** [comment]
LGTM.

**Comment by phadej** [comment]
thanks.

**Pull request merged**
